- hosts: 127.0.0.1
  connection: local
  user: root
  sudo: false
  gather_facts: false
  serial: 1

  vars_prompt:
    - name:    'username'
      prompt:  'Enter your vCenter username'
      private: no
    - name:    'password'
      prompt:  'Enter your vCenter password'
      private: yes
    - name:    'hostname'
      prompt:  'Enter the hostname for the VM'
      private: no

  tasks:
  - vsphere_guest:
      vcenter_hostname: "vmcenter.cse.ohio-state.edu"
      username: "{{ username }}"
      password: "{{ password }}"
      guest: "{{ hostname }}"
      state: powered_on
      vm_extra_config:
        vcpu.hotadd: yes
        mem.hotadd:  yes
        notes: Ansible test vm
      vm_disk:
        disk1:
          size_gb: 10
          type: thin
          datastore: CSE5472 SAN_Lun_10
      vm_nic:
        nic1:
          type: vmxnet3
          network: cse652group1
          network_type: standard
      vm_hardware:
        memory_mb: 512
        num_cpus: 1
        osid: ubuntu64guest
        scsi: paravirtual
      esxi:
        datacenter: CSEOSUDatacenter
        hostname: vh1.cse.ohio-state.edu
