- hosts: 127.0.0.1
  connection: local
  user: root
  sudo: false
  gather_facts: false
  serial: 1

  tasks:
  - vsphere_guest:
      vcenter_hostname: vmcenter.cse.ohio-state.edu
      username: casavant
      password: 
      guest: g1_jeff2
      state: powered_on
      vm_extra_config:
        vcpu.hotadd: yes
        mem.hotadd:  yes
        notes: Jeffs ansible test vm
      vm_disk:
        disk1:
          size_gb: 10
          type: thin
          datastore: CSE5472 SAN_Lun_10
      vm_nic:
        nic1:
          type: vmxnet3
          network: cse652group1
          network_type: standard
      vm_hardware:
        memory_mb: 512
        num_cpus: 1
        osid: ubuntu64guest
        scsi: paravirtual
        vm_cdrom:
          type: "iso"
          iso_path: "DatastoreName/cd-image.iso"
      esxi:
        datacenter: CSEOSUDatacenter
        hostname: vh1.cse.ohio-state.edu
