- name: uninstall unnecessary services
  apt:
    name: "{{ item }}"
    state: absent
    with_items:
      - apport
      - apport-symptoms
      - python3-apport
      - at

- name: disable anacron
  lineinfile:
    dest: /etc/crontab
    state: absent
    regexp: anacron

