---
#snort task

- name: install snort
  apt:
    pkg: "{{ item }}" 
    update_cache: yes
    cache_valid_time: 3600
    state: present
  notify: restart snort
  with_items: 
   - snort
   - oinkmaster
 
- name: configure snort
  template: >
    src=etc/snort/snort.conf.j2 dest=/etc/snort/snort.conf
    owner=root group=root mode=0644
  notify: restart snort

- name: open read permissions on snort logs
  file: >
    name="/var/log/snort"
    state="directory"
    mode="755"

- name: install oinkmaster cronjob
  template: >
    src=etc/cron.daily/oinkmaster.j2 dest=/etc/cron.daily/oinkmaster
    owner=root group=root mode=0755

- name: snort service started
  service:
    name: snort
    state: started

