- name: iptables | install iptables-persistent
  environment:
    DEBIAN_FRONTEND: noninteractive
  apt: pkg=iptables-persistent state=present
  notify:
  - Save ipv4 rules
  - Save ipv6 rules

- name: iptables | /etc/iptables dir
  file: path=/etc/iptables state=directory
  notify:
  - Save ipv4 rules
  - Save ipv6 rules

