# Vagrantfile API/syntax version. Don't touch unless you know what you're
# doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.vm.box = 'vsphere' 
    config.vm.box_url = 'https://vagrantcloud.com/ssx/boxes/vsphere-dummy/versions/1/providers/vsphere.box'

    config.vm.provider :vsphere do |vsphere|
        # The host we're going to connect to
        vsphere.host = '192.168.1.253'                            

        # The host for the new VM
        vsphere.compute_resource_name = '192.168.1.2'            

        # The resource pool for the new VM
        vsphere.resource_pool_name = 'Linux'                    

        # The template we're going to clone        
        vsphere.template_name = 'ubuntu.template.dc.sw10.net'    

        # The name of the new machine
        vsphere.name = 'bingo'                                     

        # vSphere login
        vsphere.user = 'root'                                    

        # vSphere password
        vsphere.password = 'password'                            

        # If you don't have SSL configured correctly, set this to 'true'
        vsphere.insecure = true                                    
  
    config.vm.network :public_network

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "hardened.yml"

    end
end
