# vi: set ft=ruby :
require 'yaml'

VAGRANTFILE_API_VERSION = "2"

local_settings = YAML.load_file 'vagrant_local.yml'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.vm.box = 'vsphere' 
    config.vm.box_url = 'https://vagrantcloud.com/ssx/boxes/vsphere-dummy/versions/1/providers/vsphere.box'

    config.vm.provider :vsphere do |vsphere|
        # The host we're going to connect to
        vsphere.host = 'vmcenter.cse.ohio-state.edu'

        # The host for the new VM
        vsphere.compute_resource_name = '192.168.1.2'            

        # The resource pool for the new VM
        vsphere.resource_pool_name = 'Linux'                    

        # The template we're going to clone        
        vsphere.template_name = 'ubuntu.template.dc.sw10.net'    

        # The name of the new machine
        vsphere.name = local_settings['vm_hostname']

        # vSphere login
        vsphere.user = local_settings['username']

        # vSphere password
        vsphere.password = local_settings['password']

        # If you don't have SSL configured correctly, set this to 'true'
        vsphere.insecure = true                                    
        end
  
    config.vm.network :public_network

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "hardened.yml"

    end
end
