# Add users for jeff, abby, and alex

- name: pubkeys | jeff .ssh dir
  file: path=/home/jeff/.ssh state=directory

- name: pubkeys | jeff authorized_keys file
  copy:
    src: jeff_authorizedkeys
    dest: /home/jeff/.ssh/authorized_keys
    owner: jeff
    group: users
    mode: 0644
    force: yes

- name: pubkeys | alex .ssh dir
  file: path=/home/alex/.ssh state=directory

- name: pubkeys | alex authorized_keys file
  copy:
    src: alex_authorizedkeys
    dest: /home/alex/.ssh/authorized_keys
    owner: alex
    group: users
    mode: 0644
    force: yes

- name: pubkeys | abby .ssh dir
  file: path=/home/abby/.ssh state=directory

- name: pubkeys | abby authorized_keys file
  copy:
    src: abby_authorizedkeys
    dest: /home/abby/.ssh/authorized_keys
    owner: abby
    group: users
    mode: 0644
    force: yes

