# Add users for jeff, abby, and alex

- name: users | ensure jeff .ssh exists
  file: path=/home/jeff/.ssh state=directory

- name: users | install jeff authorized_keys file
  copy:
    src: jeff_authorizedkeys
    dest: /home/jeff/.ssh/authorized_keys
    owner: jeff
    group: jeff
    mode: 0644
    force: yes

- name: users | ensure alex .ssh exists
  file: path=/home/alex/.ssh state=directory

- name: users | install abby authorized_keys file
  copy:
    src: alex_authorizedkeys
    dest: /home/alex/.ssh/authorized_keys
    owner: alex
    group: alex
    mode: 0644
    force: yes

- name: users | ensure abby .ssh exists
  file: path=/home/abby/.ssh state=directory

- name: users | install abby authorized_keys file
  copy:
    src: abby_authorizedkeys
    dest: /home/abby/.ssh/authorized_keys
    owner: abby
    group: abby
    mode: 0644
    force: yes

